apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: weblio
  labels:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/component: health-monitor
data:
  config.yaml: |
    storage:
      type: "${STORAGE_TYPE}"
      path: "${STORAGE_PATH}"
      
    alerting:
      email:
        from: "${ALERTING_EMAIL_FROM}"
        username: "${ALERTING_EMAIL_USERNAME}"
        password: "${ALERTING_EMAIL_PASSWORD}"
        host: "${ALERTING_EMAIL_HOST}"
        port: ${ALERTING_EMAIL_PORT}
        to: "${ALERTING_EMAIL_TO}"
        default-alert:
          send-on-resolved: true
          failure-threshold: ${ALERTING_EMAIL_FAILURE_THRESHOLD}
          success-threshold: ${ALERTING_EMAIL_SUCCESS_THRESHOLD}
    ui:
      title: "Weblio Status"
      description: "Monitoring the status of Weblio and its clients."
      logo: "https://weblio.se/assets/icon.svg"

    defaults: &defaults
      interval: ${DEFAULT_INTERVAL}
      alerts:
        - type: email

    http-conditions: &http-conditions
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      
    http-defaults: &http-defaults
      <<: *defaults
      conditions: *http-conditions
      
    endpoints:

    # Weblio
      - name: Website
        group: 1. Weblio
        url: "https://weblio.se"
        <<: *http-defaults
      - name: Form
        group: 1. Weblio
        url: "https://form.weblio.se"
        <<: *http-defaults
      - name: Form API
        group: 1. Weblio
        url: "https://api.form.weblio.se/health"
        <<: *http-defaults
    
    # Clients
      - name: Mulo
        group: 2. Clients
        url: "https://mulo.se"
        <<: *http-defaults
      - name: AMEA Salong
        group: 2. Clients
        url: "https://ameasalong.se"
        <<: *http-defaults
      - name: Alpaka's Coffee
        group: 2. Clients
        url: "https://alpakascoffee.com"
        <<: *http-defaults
