apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: weblio
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
      app.kubernetes.io/component: workflow-automation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/component: workflow-automation
        app.kubernetes.io/managed-by: argocd
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.37
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - mountPath: /data
              name: data
      containers:
        - name: n8n
          image: n8nio/n8n:1.114.2
          command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          ports:
            - containerPort: 5678
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          env:
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: "https://n8n.weblio.se"
            - name: GENERIC_TIMEZONE
              value: Europe/Stockholm
          envFrom:
            - secretRef:
                name: n8n-secrets
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: data
      volumes:
        - name: data
          nfs:
            path: /export/Kubernetes/weblio/n8n
            server: 192.168.86.107
